FROM golang:1.15 as build

RUN mkdir app
WORKDIR app

RUN apt-get update && apt-get install -y --no-install-recommends \
    stockfish \
    && apt-get clean

ENV PATH="/usr/games:${PATH}"
ENV STOCKFISH_PATH="stockfish"
ENV STOCKFISH_ARGS=""

COPY cmd/backend cmd/backend
COPY internal internal
COPY pkg pkg
COPY go.mod .

RUN go mod download

RUN go build -o main github.com/gmkornilov/chess-puzzle-book-backend/cmd/backend

CMD ["./main"]